language: ruby
bundler_args: --without extra
rvm:
  - 1.9.3
notifications:
  email:
    recipients:
      - rintze.zelle@gmail.com
      - karcher@u.northwestern.edu
    on_success: change
    on_failure: always
  webhooks:
    urls:
      - https://styles-update.zotero.net:8827/
    on_success: always
    on_failure: never
