language: ruby
bundler_args: "--without extra --path=~/.bundle"
rvm:
  - 2.1.1
notifications:
  email:
    recipients:
      - rintze.zelle@gmail.com
      - karcher@u.northwestern.edu
    on_success: change
    on_failure: always
  webhooks:
    urls:
      - https://styles-update.zotero.org:8827/
    on_success: always
    on_failure: never
before_install:
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
  - gem install bundle_cache
#  - bundle_cache_install
after_script:
#  - bundle_cache
env:
  global:
    BUNDLE_ARCHIVE: styles_bundle.cache
    AWS_S3_BUCKET: citationstyles-cache
    secure: GuOUVKCpBFXnQtR8ZkYehcdkVu79Ay9kbHR9ViQaPqN7H0rLgHb7LB3Is1ati85IigK26YaRX+c55rHErED2d/f6kAMvkYDCP5tCG00hll+ehbZLtxHdl/556i/pHYAmNRcHr1eWHsLSVcXtzAydyPUivhMEVxhwHhu2uyJGzCg=
